Document: pachi-data
Title: Debian pachi-data Manual
Author: <insert document author here>
Abstract: This manual describes what pachi-data is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pachi-data/pachi-data.sgml.gz

Format: postscript
Files: /usr/share/doc/pachi-data/pachi-data.ps.gz

Format: text
Files: /usr/share/doc/pachi-data/pachi-data.text.gz

Format: HTML
Index: /usr/share/doc/pachi-data/html/index.html
Files: /usr/share/doc/pachi-data/html/*.html
