COMMON_FLAGS += -DNO_THREAD_LOCAL
LDFLAGS      := -pthread -rdynamic
SYS_LIBS     := -lm -ldl
DCNN_LIBS    := -lcaffe -lboost_system -lglog -lstdc++ $(SYS_LIBS)


strip: FORCE
	cd distribute  &&  strip pachi
