COMMON_FLAGS += -DNO_THREAD_LOCAL
LDFLAGS      := -pthread -rdynamic
LIBS         := -lm -ldl
DCNN_LIBS    := -lcaffe -lboost_system -lglog -lstdc++ $(LIBS)


strip: FORCE
	cd distribute  &&  strip pachi
