COMMON_FLAGS += -DNO_THREAD_LOCAL
LDFLAGS      := -pthread -rdynamic
LIBS         := -lm -ldl
DCNN_LIBS    := -lcaffe -lopenblas -lglog -lstdc++ $(LIBS)


strip: FORCE
	cd distribute  &&  strip pachi
        ifeq ($(BUILD_KATAGO), 1)
	    cd distribute  &&  strip $(KATAGO_BINARY)
        endif
