#!/bin/bash
# get latest joseki fixes database from github.
# most up-to-date version is in 'joseki_fixes' branch.

if ! [ -f update_database ]; then
    echo "update_database: must run in josekifix/ directory"
    exit 1
fi

echo "Getting latest version of josekifix.sgf, fusekifix.sgf ..."
echo "    https://github.com/pasky/pachi/tree/joseki_fixes"
echo ""

for file in josekifix.sgf fusekifix.sgf; do
    [ -f $file ]   &&   cp $file $file.bak	# backup existing

    if wget -q -O $file  "https://github.com/pasky/pachi/raw/joseki_fixes/$file"; then	
	if [ -f $file.bak ] && cmp -s $file $file.bak; then
	    echo "$file: already up-to-date"
	else
	    echo "$file: updated to latest version"
	fi
    else
	echo "failed to download $file  (network failure ?)"
    fi    
done

echo ""

