#!/bin/bash
# This is autotest client lister.

. ./autotest-lib

printf "LAST ACTIVITY\t\t\tWFAIL#\tNAME\n"
for c in c/*; do
	client="${c#c/}"
	beacon="$(date --rfc-3339=seconds -d "1970-01-01 $(cat "$c/beacon") seconds")"
	fails="$(grep -c fail "$c/log" || :)"
	printf "$beacon\t$fails\t$client\n"
done
