#!/bin/bash
# Test uct virtual loss works
# usage: test_virtual_loss <color>

playouts=2000

get_expanded_nodes()
{
    color=$1
    echo "genmove $color" | $PACHI -d4 -t =$playouts expand_p=0 virtual_loss=10 2>&1 |
        grep "expanded nodes" | cut -d: -f2
}

[ -n "$1" ] || exit 1

nodes=`get_expanded_nodes $1`
#echo "playouts: $playouts      expanded nodes:  $nodes"

# Should get close to number of playouts nodes.

# More nodes than playouts ? great.
if [ $nodes -gt $playouts ]; then
    exit 0
fi

# Should get less than 5% difference
diff=$[ $playouts - $nodes ]
pc=$[ $diff * 100 / $playouts ]
#echo "percentage diff from playouts:  $pc%"

fail=$[$pc >= 5]
exit $fail
