#!/bin/sh
# process gtp stream and print ascii board.
# usage: gtp2board_print < file.gtp

dir=`dirname "$0"`/..
cd $dir

# we don't need any engine really, using replay because it starts up fast.
( cat; echo "showboard" ) | ./pachi -e replay --nojoseki  2>/dev/null  |
tail -24 | grep -A 24 Move | sed -e 's/^= //'
