Index: src/Makefile
===================================================================
--- src.orig/Makefile	2018-08-05 20:53:52.000000000 +0100
+++ src/Makefile	2018-08-05 21:02:10.393659113 +0100
@@ -12,7 +12,7 @@
 # Otherwise you may do without to enable more aggressive optimizations
 # for this machine only.
 
-# GENERIC=1
+GENERIC=1
 
 # Do you compile on Windows instead of Linux ?
 # Please note that performance may not be optimal.
